server:
  port: 8887
logging:
  file: userManager.log
  path: logs
spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    data-password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
