server:
  port: 8899
logging:
  file: mylog.log
  path: logs

spring:
  application:
    name: mytTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
